# Generated by Django 4.0.2 on 2023-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tasklabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tasklabels'),
        ),
    ]
