# Generated by Django 4.0.2 on 2023-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabels',
            name='task_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
