# Generated by Django 4.0.2 on 2023-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tasklabels_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_label',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('gym', 'Gym'), ('other', 'Other')], default='other', max_length=30, null=True),
        ),
    ]
